### ISSUE TITLE
Add Support for TablePlus installed via Setapp

### ISSUE THREAD

**Issue by marcel-za** [aubreypwd/localwp-tableplus#13]
I've installed & enabled the LocalWP Tableplus extension.

I have Tableplus installed & running on my Mac.

However, when opening any site's "Database" tab in LocalWP, the "Open Tableplus" link is disabled/grey/unclickable.

Local v6.0.0+5444
Tableplus extensions v1.0.5
Tableplus build 371 (Managed by Setapp)

![CleanShot 2021-07-13 at 10 08 46](https://user-images.githubusercontent.com/28527561/125415953-12868029-648a-42f2-af29-d8659482b8af.png)

**Comment by tharindutpk** [comment]
I'm having the same issue

**Comment by bzaromedia** [comment]
I am also having the exact same issue

**Comment by tharindutpk** [comment]
I got it fixed. I had to uninstall and re-install TablePlus on macOS. It's available on mac app store.

**Comment by marcel-za** [comment]
I'm using the Setapp version & I installed it after installing Local. So not sure if that method will work for me.

**Comment by aubreypwd** [comment]
Another reason it's usually disabled is because it couldn't modify the `/tmp/mysql.sock` file, in a Terminal I would try `sudo rm /tmp/mysql.sock` and switch back and forth between the Overview and Database tab again.

We have no control over the permissions of that file... But it could also be that SetApp is installing TablePlus in a different location other than `/Applications`?

**Comment by marcel-za** [comment]
> But it could also be that SetApp is installing TablePlus in a different location other than  @`/Applications`?

Yes, you've nailed it @aubreypwd : Setapp uses '/Applications/Setapp'. Is there a work-around?

**Comment by bzaromedia** [comment]
Thanks for that

**Comment by mvaneijgen** [comment]
Installed TablePlus via Setapp and moved the application to the Application folder, which makes it work with local.

**Comment by ironicmoka** [comment]
It works even via drag 'n drop an alias of the app (even better a symlink I guess, but the alias was enough)

**Comment by aubreypwd** [comment]
FYI all I have noticed that some apps can register themselves as the handler for `mysql://` which we use to trigger TablePlus to open (when it's assigned as the handler), so likely re-installing just set itself as the handler for this protocol.

**Comment by aubreypwd** [comment]
If everyone here can test https://github.com/aubreypwd/localwp-tableplus/releases/tag/v1.1.0-rc1 that would be great, give feedback on this issue and let's see if that helps!

**Comment by chrismccoy** [comment]
> If everyone here can test https://github.com/aubreypwd/localwp-tableplus/releases/tag/v1.1.0-rc1 that would be great, give feedback on this issue and let's see if that helps!

i have tested and it works through setapp, im on latest macos monterey

**Comment by ironicmoka** [comment]
Tried on MacOS BigSur and Local Version 6.1.5+5536, it works.

Deleted first the TablePlus alias in /Applications (it was working as a workaround) to confirm:

stable + alias: it works.

stable - alias: doesn't work.

v1.1.0.rc1 - alias: it works.

**Comment by aubreypwd** [comment]
Cool, I will try and get this released soon! Thanks for testing!

**Comment by aubreypwd** [comment]
This has been [released](https://github.com/aubreypwd/localwp-tableplus/releases/tag/v1.1.0), if you guys here could give it a test to confirm it's working I would appreciate it!

**Comment by chrismccoy** [comment]
not working here, have it installed through setapp, but when site is active, the tableplus tab is greyed out, adminer works fine, no option to click open table plus, i have tried even with tableplus already opened. even tried rebooting

im on local 6.1.7+5610
